### ISSUE TITLE
Update to spring-boot 1.3.3

### ISSUE THREAD

**Issue by ptahchiev** [spring-projects/spring-batch-admin-samples#2]
Please update to latest spring-boot. I tried it but it shows this error:

```
Caused by: java.lang.IllegalStateException: @Scheduled method 'removeInactiveExecutions' found on bean target class 'SimpleJobService' but not found in any interface(s) for a dynamic proxy. Either pull the method up to a declared interface or switch to subclass (CGLIB) proxies by setting proxy-target-class/proxyTargetClass to 'true'.
    at org.springframework.scheduling.annotation.ScheduledAnnotationBeanPostProcessor.processScheduled(ScheduledAnnotationBeanPostProcessor.java:287)
    at org.springframework.scheduling.annotation.ScheduledAnnotationBeanPostProcessor.postProcessAfterInitialization(ScheduledAnnotationBeanPostProcessor.java:258)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:422)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.postProcessObjectFromFactoryBean(AbstractAutowireCapableBeanFactory.java:1723)
    at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:130)
    ... 26 more

```

**Comment by guylabs** [comment]
Hi @ptahchiev,

I could fix the issue and created the #7 pull request which also upgrades to Spring Boot 1.3.5.RELEASE. Lets hope that the pull request gets accepted and is merged to master.

Regards,

Guy

**Comment by entmatrescu** [comment]
@guylabs Thanks for the solution, it worked!

**Comment by fmbenhassine** [comment]
Closing this issue as the project is being moved to the [spring-attic](https://github.com/spring-attic).
